### PR TITLE
Fix for skiplink issue. Iissue#76

### PR DESCRIPTION
**Pull request by masv-scb**
Fixt problem with skiplink not working.

### CODE REVIEW

**Review by MikaelNordberg — APPROVED** [review]
I think it looks good. However we need Johannes appoval about the screen reader stuff.

**Review by JohannesFinsveen — CHANGES_REQUESTED** [review]
I migth be missing something as a github-newbie, but it seems nothing is added to the Panels. 
If so, should we remove them untill we have a text for them? Or not?

**Comment by JohannesFinsveen** [comment]
Or is it better to use a draft text and get started :-)

**Review by MikaelNordberg — APPROVED** [review]
Looks good

**Comment by JohannesFinsveen** [comment]
Very good!

**Review by JohannesFinsveen — APPROVED** [review]
Very good 2 :-)

**Pull request merged**
