### PR TITLE
Pxapi2/feature/unittests px file

### PR DESCRIPTION
**Pull request by KentMossback**
Added PxFile-database unittests

### CODE REVIEW

**Review by MikaelNordberg — APPROVED** [review]
Looks good

**Comment by likp** [comment]
Do we really  need to have a copy of the database? could we not use the one in the PxWeb project?

**Comment by likp** [comment]
@KentMossback any updates on this?

**Comment by KentMossback** [comment]
I can give it another try to use the px-file in the PxWeb project. I was not able to get that to work.

**Comment by KentMossback** [comment]
@likp database copy now removed from unittest project. Tests read from database in PxWeb project instead

**Review by likp — APPROVED** [review]

**Pull request merged**
